name: Deploy Dist

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Clone Repository
        run: |
          echo "Cloning the repository"
          git clone https://github.com/${{ github.repository }}.git
