name: deploy dist
on: [push,workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: git code
        run: |
            echo "cloning a repo"
            echo "${{ toJson(github)}}"
            git clone https://github.com/webamitkumar/gitHub-action.git